version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys: ["node_modules"]
      - run:
          name: install dependencies
          command: |
            npm install
      - run:
          name: linting code
          command: |
            npm run lint
      - save_cache:
          paths: ["node_modules"]
          key: "node_modules"

  #build

  #create-docker-image

  #deploy-k8s-cluster

  #deploy-app-to-k8s


workflows:
  default:
    jobs:
      - lint